const Types = {
  SET_COSTUMER:'@shop/SET_COSTUMER',
  REQUEST_PETSHOPS:'@sho p/REQUEST_PETSHOPS',
  SET_PETSHOPS:'@shop/SET_PETSHOPS',
  SET_PETSHOP_MAP_SELECTED: '@shop/SET_PETSHOP_MAP_SELECTED',
  SET_MAP_CENTER:'@shop/SET_MAP_CENTER',
  REQUEST_PETSHOP:'@shop/REQUEST_PETSHOP',
  SET_PETSHOP:'@shop/SET_PETSHOP',
  TOOGLE_CART_PRODUCT:'@shop/TOOGLE_CART_PRODUCT',
}; 

export default Types