const Types = {
  CREATE_MARKET_REQUEST: '@market/CREATE_MARKET_REQUEST',
  CREATE_MARKET_SUCCESS: '@market/CREATE_MARKET_SUCCESS',

  READ_MARKETS_REQUEST: '@market/READ_MARKETS_REQUEST',
  READ_MARKETS_SUCCESS: '@market/READ_MARKETS_SUCCESS',

  READ_MARKET_REQUEST: '@market/READ_MARKET_REQUEST',
  READ_MARKET_SUCCESS: '@market/READ_MARKET_SUCCESS',

  UPDATE_MARKET_REQUEST: '@market/UPDATE_MARKET_REQUEST',
  UPDATE_MARKET_SUCCESS: '@market/UPDATE_MARKET_SUCCESS',

  DELETE_MARKET_REQUEST: '@market/DELETE_MARKET_REQUEST',
  DELETE_MARKET_SUCCESS: '@market/DELETE_MARKET_SUCCESS',
};

export default Types;
